export class ArticleItemBean {
  title: string = '';
  content: string = '';
  // imagesUrl: Array<NewsFile> = [new NewsFile()];
  source: string = '';
  author: string = '';
  shareUser: string = '';
  niceDate: string = '';
  link: string = '';
  superChapterName: string = '';
  chapterName: string = '';
}

// export class NewsFile {
//   id: Number = 0;
//   url: String = '';
//   type: number = 0;
//   newsId: number = 0;
// }